services: 
  transaction: 
    image: mmkmou/transactions:develop
    environment:
      DATASOURCE_USERNAME: transaction
      DATASOURCE_PASSWORD: passer
      DATASOURCE_URL: jdbc:postgresql://db:5432/transaction
    ports:
      - "8081:8081"
    networks:
      - dbnet 

  db: 
    environment: 
      POSTGRES_PASSWORD: passer
      POSTGRES_USER: transaction
      POSTGRES_DB: transaction
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - dbnet
    image: postgres


volumes:
  dbdata: 
networks:
  dbnet:

      
